#!/bin/bash

ARGS="-v -i"
if [ -n "$*" ]; then
	ARGS=$*
fi
export PATH=$PATH:/opt/circonus/bin:/opt/omni/bin

gmake -v >/dev/null 2>&1
if [ $? -eq 0 ]; then
  export MAKE=gmake
fi
npm config set color false
(cd ../../src/js && npm install)
npm install
exec node ./runtests.js $ARGS
