#!/bin/bash

ARGS="-v -i"
if [ -n "$*" ]; then
	ARGS=$*
fi

PATH=$PATH:/opt/circonus/bin:/opt/omni/bin

for GCCPATH in "`find /opt -maxdepth 1 -type d -name gcc\* | sort -r`"; do
  PATH=$PATH:$GCCPATH/bin
done

export PATH

gmake -v >/dev/null 2>&1
if [ $? -eq 0 ]; then
  export MAKE=gmake
fi

if [ "x$SKIP_NPM_INSTALL" != "x1" ]; then
	npm config set color false
	(cd ../../src/js && npm install)
	npm install
fi
exec node ./runtests.js $ARGS
