package com.omniti.reconnoiter;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckStatus.proto

public final class CheckStatus {
  private CheckStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MetricOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required int32 metricType = 2;
    boolean hasMetricType();
    int getMetricType();
    
    // optional double valueDbl = 3;
    boolean hasValueDbl();
    double getValueDbl();
    
    // optional int64 valueI64 = 4;
    boolean hasValueI64();
    long getValueI64();
    
    // optional uint64 valueUI64 = 5;
    boolean hasValueUI64();
    long getValueUI64();
    
    // optional int32 valueI32 = 6;
    boolean hasValueI32();
    int getValueI32();
    
    // optional uint32 valueUI32 = 7;
    boolean hasValueUI32();
    int getValueUI32();
    
    // optional string valueStr = 8;
    boolean hasValueStr();
    String getValueStr();
  }
  public static final class Metric extends
      com.google.protobuf.GeneratedMessage
      implements MetricOrBuilder {
    // Use Metric.newBuilder() to construct.
    private Metric(Builder builder) {
      super(builder);
    }
    private Metric(boolean noInit) {}
    
    private static final Metric defaultInstance;
    public static Metric getDefaultInstance() {
      return defaultInstance;
    }
    
    public Metric getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CheckStatus.internal_static_Metric_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CheckStatus.internal_static_Metric_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 metricType = 2;
    public static final int METRICTYPE_FIELD_NUMBER = 2;
    private int metricType_;
    public boolean hasMetricType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMetricType() {
      return metricType_;
    }
    
    // optional double valueDbl = 3;
    public static final int VALUEDBL_FIELD_NUMBER = 3;
    private double valueDbl_;
    public boolean hasValueDbl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getValueDbl() {
      return valueDbl_;
    }
    
    // optional int64 valueI64 = 4;
    public static final int VALUEI64_FIELD_NUMBER = 4;
    private long valueI64_;
    public boolean hasValueI64() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getValueI64() {
      return valueI64_;
    }
    
    // optional uint64 valueUI64 = 5;
    public static final int VALUEUI64_FIELD_NUMBER = 5;
    private long valueUI64_;
    public boolean hasValueUI64() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getValueUI64() {
      return valueUI64_;
    }
    
    // optional int32 valueI32 = 6;
    public static final int VALUEI32_FIELD_NUMBER = 6;
    private int valueI32_;
    public boolean hasValueI32() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getValueI32() {
      return valueI32_;
    }
    
    // optional uint32 valueUI32 = 7;
    public static final int VALUEUI32_FIELD_NUMBER = 7;
    private int valueUI32_;
    public boolean hasValueUI32() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getValueUI32() {
      return valueUI32_;
    }
    
    // optional string valueStr = 8;
    public static final int VALUESTR_FIELD_NUMBER = 8;
    private java.lang.Object valueStr_;
    public boolean hasValueStr() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getValueStr() {
      java.lang.Object ref = valueStr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          valueStr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueStrBytes() {
      java.lang.Object ref = valueStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        valueStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
      metricType_ = 0;
      valueDbl_ = 0D;
      valueI64_ = 0L;
      valueUI64_ = 0L;
      valueI32_ = 0;
      valueUI32_ = 0;
      valueStr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMetricType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, metricType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, valueDbl_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, valueI64_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, valueUI64_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, valueI32_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, valueUI32_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getValueStrBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, metricType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, valueDbl_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, valueI64_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, valueUI64_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, valueI32_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, valueUI32_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getValueStrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static CheckStatus.Metric parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CheckStatus.Metric parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Metric parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CheckStatus.Metric parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Metric parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CheckStatus.Metric parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Metric parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CheckStatus.Metric parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CheckStatus.Metric parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CheckStatus.Metric parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CheckStatus.Metric prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CheckStatus.MetricOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CheckStatus.internal_static_Metric_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CheckStatus.internal_static_Metric_fieldAccessorTable;
      }
      
      // Construct using CheckStatus.Metric.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        metricType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        valueDbl_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        valueI64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        valueUI64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        valueI32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        valueUI32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        valueStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CheckStatus.Metric.getDescriptor();
      }
      
      public CheckStatus.Metric getDefaultInstanceForType() {
        return CheckStatus.Metric.getDefaultInstance();
      }
      
      public CheckStatus.Metric build() {
        CheckStatus.Metric result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private CheckStatus.Metric buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CheckStatus.Metric result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public CheckStatus.Metric buildPartial() {
        CheckStatus.Metric result = new CheckStatus.Metric(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.metricType_ = metricType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.valueDbl_ = valueDbl_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.valueI64_ = valueI64_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.valueUI64_ = valueUI64_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.valueI32_ = valueI32_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.valueUI32_ = valueUI32_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.valueStr_ = valueStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CheckStatus.Metric) {
          return mergeFrom((CheckStatus.Metric)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CheckStatus.Metric other) {
        if (other == CheckStatus.Metric.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasMetricType()) {
          setMetricType(other.getMetricType());
        }
        if (other.hasValueDbl()) {
          setValueDbl(other.getValueDbl());
        }
        if (other.hasValueI64()) {
          setValueI64(other.getValueI64());
        }
        if (other.hasValueUI64()) {
          setValueUI64(other.getValueUI64());
        }
        if (other.hasValueI32()) {
          setValueI32(other.getValueI32());
        }
        if (other.hasValueUI32()) {
          setValueUI32(other.getValueUI32());
        }
        if (other.hasValueStr()) {
          setValueStr(other.getValueStr());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasMetricType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              metricType_ = input.readInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              valueDbl_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              valueI64_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              valueUI64_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              valueI32_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              valueUI32_ = input.readUInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              valueStr_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required int32 metricType = 2;
      private int metricType_ ;
      public boolean hasMetricType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMetricType() {
        return metricType_;
      }
      public Builder setMetricType(int value) {
        bitField0_ |= 0x00000002;
        metricType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMetricType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        metricType_ = 0;
        onChanged();
        return this;
      }
      
      // optional double valueDbl = 3;
      private double valueDbl_ ;
      public boolean hasValueDbl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getValueDbl() {
        return valueDbl_;
      }
      public Builder setValueDbl(double value) {
        bitField0_ |= 0x00000004;
        valueDbl_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueDbl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        valueDbl_ = 0D;
        onChanged();
        return this;
      }
      
      // optional int64 valueI64 = 4;
      private long valueI64_ ;
      public boolean hasValueI64() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getValueI64() {
        return valueI64_;
      }
      public Builder setValueI64(long value) {
        bitField0_ |= 0x00000008;
        valueI64_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueI64() {
        bitField0_ = (bitField0_ & ~0x00000008);
        valueI64_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 valueUI64 = 5;
      private long valueUI64_ ;
      public boolean hasValueUI64() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getValueUI64() {
        return valueUI64_;
      }
      public Builder setValueUI64(long value) {
        bitField0_ |= 0x00000010;
        valueUI64_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueUI64() {
        bitField0_ = (bitField0_ & ~0x00000010);
        valueUI64_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 valueI32 = 6;
      private int valueI32_ ;
      public boolean hasValueI32() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getValueI32() {
        return valueI32_;
      }
      public Builder setValueI32(int value) {
        bitField0_ |= 0x00000020;
        valueI32_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueI32() {
        bitField0_ = (bitField0_ & ~0x00000020);
        valueI32_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 valueUI32 = 7;
      private int valueUI32_ ;
      public boolean hasValueUI32() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getValueUI32() {
        return valueUI32_;
      }
      public Builder setValueUI32(int value) {
        bitField0_ |= 0x00000040;
        valueUI32_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueUI32() {
        bitField0_ = (bitField0_ & ~0x00000040);
        valueUI32_ = 0;
        onChanged();
        return this;
      }
      
      // optional string valueStr = 8;
      private java.lang.Object valueStr_ = "";
      public boolean hasValueStr() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getValueStr() {
        java.lang.Object ref = valueStr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          valueStr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValueStr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        valueStr_ = value;
        onChanged();
        return this;
      }
      public Builder clearValueStr() {
        bitField0_ = (bitField0_ & ~0x00000080);
        valueStr_ = getDefaultInstance().getValueStr();
        onChanged();
        return this;
      }
      void setValueStr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        valueStr_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Metric)
    }
    
    static {
      defaultInstance = new Metric(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Metric)
  }
  
  public interface StatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 available = 1;
    boolean hasAvailable();
    int getAvailable();
    
    // required int32 state = 2;
    boolean hasState();
    int getState();
    
    // required int32 duration = 3;
    boolean hasDuration();
    int getDuration();
    
    // required string status = 4;
    boolean hasStatus();
    String getStatus();
  }
  public static final class Status extends
      com.google.protobuf.GeneratedMessage
      implements StatusOrBuilder {
    // Use Status.newBuilder() to construct.
    private Status(Builder builder) {
      super(builder);
    }
    private Status(boolean noInit) {}
    
    private static final Status defaultInstance;
    public static Status getDefaultInstance() {
      return defaultInstance;
    }
    
    public Status getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CheckStatus.internal_static_Status_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CheckStatus.internal_static_Status_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 available = 1;
    public static final int AVAILABLE_FIELD_NUMBER = 1;
    private int available_;
    public boolean hasAvailable() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAvailable() {
      return available_;
    }
    
    // required int32 state = 2;
    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getState() {
      return state_;
    }
    
    // required int32 duration = 3;
    public static final int DURATION_FIELD_NUMBER = 3;
    private int duration_;
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getDuration() {
      return duration_;
    }
    
    // required string status = 4;
    public static final int STATUS_FIELD_NUMBER = 4;
    private java.lang.Object status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          status_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      available_ = 0;
      state_ = 0;
      duration_ = 0;
      status_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAvailable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDuration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, available_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, state_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, duration_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getStatusBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, available_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, state_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, duration_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStatusBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static CheckStatus.Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CheckStatus.Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CheckStatus.Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CheckStatus.Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CheckStatus.Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CheckStatus.Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CheckStatus.Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CheckStatus.Status prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CheckStatus.StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CheckStatus.internal_static_Status_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CheckStatus.internal_static_Status_fieldAccessorTable;
      }
      
      // Construct using CheckStatus.Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        available_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        duration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CheckStatus.Status.getDescriptor();
      }
      
      public CheckStatus.Status getDefaultInstanceForType() {
        return CheckStatus.Status.getDefaultInstance();
      }
      
      public CheckStatus.Status build() {
        CheckStatus.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private CheckStatus.Status buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CheckStatus.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public CheckStatus.Status buildPartial() {
        CheckStatus.Status result = new CheckStatus.Status(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.available_ = available_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.duration_ = duration_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CheckStatus.Status) {
          return mergeFrom((CheckStatus.Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CheckStatus.Status other) {
        if (other == CheckStatus.Status.getDefaultInstance()) return this;
        if (other.hasAvailable()) {
          setAvailable(other.getAvailable());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAvailable()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        if (!hasDuration()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              available_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              state_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              duration_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              status_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 available = 1;
      private int available_ ;
      public boolean hasAvailable() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAvailable() {
        return available_;
      }
      public Builder setAvailable(int value) {
        bitField0_ |= 0x00000001;
        available_ = value;
        onChanged();
        return this;
      }
      public Builder clearAvailable() {
        bitField0_ = (bitField0_ & ~0x00000001);
        available_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 state = 2;
      private int state_ ;
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getState() {
        return state_;
      }
      public Builder setState(int value) {
        bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 duration = 3;
      private int duration_ ;
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getDuration() {
        return duration_;
      }
      public Builder setDuration(int value) {
        bitField0_ |= 0x00000004;
        duration_ = value;
        onChanged();
        return this;
      }
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000004);
        duration_ = 0;
        onChanged();
        return this;
      }
      
      // required string status = 4;
      private java.lang.Object status_ = "";
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStatus(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      void setStatus(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Status)
    }
    
    static {
      defaultInstance = new Status(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Status)
  }
  
  public interface MetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // required string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class Metadata extends
      com.google.protobuf.GeneratedMessage
      implements MetadataOrBuilder {
    // Use Metadata.newBuilder() to construct.
    private Metadata(Builder builder) {
      super(builder);
    }
    private Metadata(boolean noInit) {}
    
    private static final Metadata defaultInstance;
    public static Metadata getDefaultInstance() {
      return defaultInstance;
    }
    
    public Metadata getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CheckStatus.internal_static_Metadata_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CheckStatus.internal_static_Metadata_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static CheckStatus.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CheckStatus.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CheckStatus.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CheckStatus.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CheckStatus.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CheckStatus.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CheckStatus.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CheckStatus.Metadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CheckStatus.MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CheckStatus.internal_static_Metadata_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CheckStatus.internal_static_Metadata_fieldAccessorTable;
      }
      
      // Construct using CheckStatus.Metadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CheckStatus.Metadata.getDescriptor();
      }
      
      public CheckStatus.Metadata getDefaultInstanceForType() {
        return CheckStatus.Metadata.getDefaultInstance();
      }
      
      public CheckStatus.Metadata build() {
        CheckStatus.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private CheckStatus.Metadata buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CheckStatus.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public CheckStatus.Metadata buildPartial() {
        CheckStatus.Metadata result = new CheckStatus.Metadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CheckStatus.Metadata) {
          return mergeFrom((CheckStatus.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CheckStatus.Metadata other) {
        if (other == CheckStatus.Metadata.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // required string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Metadata)
    }
    
    static {
      defaultInstance = new Metadata(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Metadata)
  }
  
  public interface BundleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .Status status = 1;
    boolean hasStatus();
    CheckStatus.Status getStatus();
    CheckStatus.StatusOrBuilder getStatusOrBuilder();
    
    // repeated .Metric metrics = 2;
    java.util.List<CheckStatus.Metric> 
        getMetricsList();
    CheckStatus.Metric getMetrics(int index);
    int getMetricsCount();
    java.util.List<? extends CheckStatus.MetricOrBuilder> 
        getMetricsOrBuilderList();
    CheckStatus.MetricOrBuilder getMetricsOrBuilder(
        int index);
    
    // repeated .Metadata metadata = 3;
    java.util.List<CheckStatus.Metadata> 
        getMetadataList();
    CheckStatus.Metadata getMetadata(int index);
    int getMetadataCount();
    java.util.List<? extends CheckStatus.MetadataOrBuilder> 
        getMetadataOrBuilderList();
    CheckStatus.MetadataOrBuilder getMetadataOrBuilder(
        int index);
  }
  public static final class Bundle extends
      com.google.protobuf.GeneratedMessage
      implements BundleOrBuilder {
    // Use Bundle.newBuilder() to construct.
    private Bundle(Builder builder) {
      super(builder);
    }
    private Bundle(boolean noInit) {}
    
    private static final Bundle defaultInstance;
    public static Bundle getDefaultInstance() {
      return defaultInstance;
    }
    
    public Bundle getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CheckStatus.internal_static_Bundle_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CheckStatus.internal_static_Bundle_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .Status status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private CheckStatus.Status status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public CheckStatus.Status getStatus() {
      return status_;
    }
    public CheckStatus.StatusOrBuilder getStatusOrBuilder() {
      return status_;
    }
    
    // repeated .Metric metrics = 2;
    public static final int METRICS_FIELD_NUMBER = 2;
    private java.util.List<CheckStatus.Metric> metrics_;
    public java.util.List<CheckStatus.Metric> getMetricsList() {
      return metrics_;
    }
    public java.util.List<? extends CheckStatus.MetricOrBuilder> 
        getMetricsOrBuilderList() {
      return metrics_;
    }
    public int getMetricsCount() {
      return metrics_.size();
    }
    public CheckStatus.Metric getMetrics(int index) {
      return metrics_.get(index);
    }
    public CheckStatus.MetricOrBuilder getMetricsOrBuilder(
        int index) {
      return metrics_.get(index);
    }
    
    // repeated .Metadata metadata = 3;
    public static final int METADATA_FIELD_NUMBER = 3;
    private java.util.List<CheckStatus.Metadata> metadata_;
    public java.util.List<CheckStatus.Metadata> getMetadataList() {
      return metadata_;
    }
    public java.util.List<? extends CheckStatus.MetadataOrBuilder> 
        getMetadataOrBuilderList() {
      return metadata_;
    }
    public int getMetadataCount() {
      return metadata_.size();
    }
    public CheckStatus.Metadata getMetadata(int index) {
      return metadata_.get(index);
    }
    public CheckStatus.MetadataOrBuilder getMetadataOrBuilder(
        int index) {
      return metadata_.get(index);
    }
    
    private void initFields() {
      status_ = CheckStatus.Status.getDefaultInstance();
      metrics_ = java.util.Collections.emptyList();
      metadata_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasStatus()) {
        if (!getStatus().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getMetricsCount(); i++) {
        if (!getMetrics(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getMetadataCount(); i++) {
        if (!getMetadata(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, status_);
      }
      for (int i = 0; i < metrics_.size(); i++) {
        output.writeMessage(2, metrics_.get(i));
      }
      for (int i = 0; i < metadata_.size(); i++) {
        output.writeMessage(3, metadata_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, status_);
      }
      for (int i = 0; i < metrics_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, metrics_.get(i));
      }
      for (int i = 0; i < metadata_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, metadata_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static CheckStatus.Bundle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CheckStatus.Bundle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Bundle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CheckStatus.Bundle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Bundle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CheckStatus.Bundle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CheckStatus.Bundle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CheckStatus.Bundle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CheckStatus.Bundle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CheckStatus.Bundle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CheckStatus.Bundle prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CheckStatus.BundleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CheckStatus.internal_static_Bundle_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CheckStatus.internal_static_Bundle_fieldAccessorTable;
      }
      
      // Construct using CheckStatus.Bundle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStatusFieldBuilder();
          getMetricsFieldBuilder();
          getMetadataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (statusBuilder_ == null) {
          status_ = CheckStatus.Status.getDefaultInstance();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (metricsBuilder_ == null) {
          metrics_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          metricsBuilder_.clear();
        }
        if (metadataBuilder_ == null) {
          metadata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          metadataBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CheckStatus.Bundle.getDescriptor();
      }
      
      public CheckStatus.Bundle getDefaultInstanceForType() {
        return CheckStatus.Bundle.getDefaultInstance();
      }
      
      public CheckStatus.Bundle build() {
        CheckStatus.Bundle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private CheckStatus.Bundle buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CheckStatus.Bundle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public CheckStatus.Bundle buildPartial() {
        CheckStatus.Bundle result = new CheckStatus.Bundle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        if (metricsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            metrics_ = java.util.Collections.unmodifiableList(metrics_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.metrics_ = metrics_;
        } else {
          result.metrics_ = metricsBuilder_.build();
        }
        if (metadataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            metadata_ = java.util.Collections.unmodifiableList(metadata_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CheckStatus.Bundle) {
          return mergeFrom((CheckStatus.Bundle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CheckStatus.Bundle other) {
        if (other == CheckStatus.Bundle.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        if (metricsBuilder_ == null) {
          if (!other.metrics_.isEmpty()) {
            if (metrics_.isEmpty()) {
              metrics_ = other.metrics_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMetricsIsMutable();
              metrics_.addAll(other.metrics_);
            }
            onChanged();
          }
        } else {
          if (!other.metrics_.isEmpty()) {
            if (metricsBuilder_.isEmpty()) {
              metricsBuilder_.dispose();
              metricsBuilder_ = null;
              metrics_ = other.metrics_;
              bitField0_ = (bitField0_ & ~0x00000002);
              metricsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMetricsFieldBuilder() : null;
            } else {
              metricsBuilder_.addAllMessages(other.metrics_);
            }
          }
        }
        if (metadataBuilder_ == null) {
          if (!other.metadata_.isEmpty()) {
            if (metadata_.isEmpty()) {
              metadata_ = other.metadata_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMetadataIsMutable();
              metadata_.addAll(other.metadata_);
            }
            onChanged();
          }
        } else {
          if (!other.metadata_.isEmpty()) {
            if (metadataBuilder_.isEmpty()) {
              metadataBuilder_.dispose();
              metadataBuilder_ = null;
              metadata_ = other.metadata_;
              bitField0_ = (bitField0_ & ~0x00000004);
              metadataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMetadataFieldBuilder() : null;
            } else {
              metadataBuilder_.addAllMessages(other.metadata_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasStatus()) {
          if (!getStatus().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getMetricsCount(); i++) {
          if (!getMetrics(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getMetadataCount(); i++) {
          if (!getMetadata(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              CheckStatus.Status.Builder subBuilder = CheckStatus.Status.newBuilder();
              if (hasStatus()) {
                subBuilder.mergeFrom(getStatus());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStatus(subBuilder.buildPartial());
              break;
            }
            case 18: {
              CheckStatus.Metric.Builder subBuilder = CheckStatus.Metric.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMetrics(subBuilder.buildPartial());
              break;
            }
            case 26: {
              CheckStatus.Metadata.Builder subBuilder = CheckStatus.Metadata.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMetadata(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .Status status = 1;
      private CheckStatus.Status status_ = CheckStatus.Status.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          CheckStatus.Status, CheckStatus.Status.Builder, CheckStatus.StatusOrBuilder> statusBuilder_;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public CheckStatus.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      public Builder setStatus(CheckStatus.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setStatus(
          CheckStatus.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeStatus(CheckStatus.Status value) {
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              status_ != CheckStatus.Status.getDefaultInstance()) {
            status_ =
              CheckStatus.Status.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = CheckStatus.Status.getDefaultInstance();
          onChanged();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public CheckStatus.Status.Builder getStatusBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      public CheckStatus.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          CheckStatus.Status, CheckStatus.Status.Builder, CheckStatus.StatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              CheckStatus.Status, CheckStatus.Status.Builder, CheckStatus.StatusOrBuilder>(
                  status_,
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }
      
      // repeated .Metric metrics = 2;
      private java.util.List<CheckStatus.Metric> metrics_ =
        java.util.Collections.emptyList();
      private void ensureMetricsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          metrics_ = new java.util.ArrayList<CheckStatus.Metric>(metrics_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          CheckStatus.Metric, CheckStatus.Metric.Builder, CheckStatus.MetricOrBuilder> metricsBuilder_;
      
      public java.util.List<CheckStatus.Metric> getMetricsList() {
        if (metricsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metrics_);
        } else {
          return metricsBuilder_.getMessageList();
        }
      }
      public int getMetricsCount() {
        if (metricsBuilder_ == null) {
          return metrics_.size();
        } else {
          return metricsBuilder_.getCount();
        }
      }
      public CheckStatus.Metric getMetrics(int index) {
        if (metricsBuilder_ == null) {
          return metrics_.get(index);
        } else {
          return metricsBuilder_.getMessage(index);
        }
      }
      public Builder setMetrics(
          int index, CheckStatus.Metric value) {
        if (metricsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsIsMutable();
          metrics_.set(index, value);
          onChanged();
        } else {
          metricsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMetrics(
          int index, CheckStatus.Metric.Builder builderForValue) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          metrics_.set(index, builderForValue.build());
          onChanged();
        } else {
          metricsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMetrics(CheckStatus.Metric value) {
        if (metricsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsIsMutable();
          metrics_.add(value);
          onChanged();
        } else {
          metricsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMetrics(
          int index, CheckStatus.Metric value) {
        if (metricsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsIsMutable();
          metrics_.add(index, value);
          onChanged();
        } else {
          metricsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMetrics(
          CheckStatus.Metric.Builder builderForValue) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          metrics_.add(builderForValue.build());
          onChanged();
        } else {
          metricsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMetrics(
          int index, CheckStatus.Metric.Builder builderForValue) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          metrics_.add(index, builderForValue.build());
          onChanged();
        } else {
          metricsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMetrics(
          java.lang.Iterable<? extends CheckStatus.Metric> values) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          super.addAll(values, metrics_);
          onChanged();
        } else {
          metricsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMetrics() {
        if (metricsBuilder_ == null) {
          metrics_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          metricsBuilder_.clear();
        }
        return this;
      }
      public Builder removeMetrics(int index) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          metrics_.remove(index);
          onChanged();
        } else {
          metricsBuilder_.remove(index);
        }
        return this;
      }
      public CheckStatus.Metric.Builder getMetricsBuilder(
          int index) {
        return getMetricsFieldBuilder().getBuilder(index);
      }
      public CheckStatus.MetricOrBuilder getMetricsOrBuilder(
          int index) {
        if (metricsBuilder_ == null) {
          return metrics_.get(index);  } else {
          return metricsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends CheckStatus.MetricOrBuilder> 
           getMetricsOrBuilderList() {
        if (metricsBuilder_ != null) {
          return metricsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metrics_);
        }
      }
      public CheckStatus.Metric.Builder addMetricsBuilder() {
        return getMetricsFieldBuilder().addBuilder(
            CheckStatus.Metric.getDefaultInstance());
      }
      public CheckStatus.Metric.Builder addMetricsBuilder(
          int index) {
        return getMetricsFieldBuilder().addBuilder(
            index, CheckStatus.Metric.getDefaultInstance());
      }
      public java.util.List<CheckStatus.Metric.Builder> 
           getMetricsBuilderList() {
        return getMetricsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CheckStatus.Metric, CheckStatus.Metric.Builder, CheckStatus.MetricOrBuilder> 
          getMetricsFieldBuilder() {
        if (metricsBuilder_ == null) {
          metricsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CheckStatus.Metric, CheckStatus.Metric.Builder, CheckStatus.MetricOrBuilder>(
                  metrics_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          metrics_ = null;
        }
        return metricsBuilder_;
      }
      
      // repeated .Metadata metadata = 3;
      private java.util.List<CheckStatus.Metadata> metadata_ =
        java.util.Collections.emptyList();
      private void ensureMetadataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          metadata_ = new java.util.ArrayList<CheckStatus.Metadata>(metadata_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          CheckStatus.Metadata, CheckStatus.Metadata.Builder, CheckStatus.MetadataOrBuilder> metadataBuilder_;
      
      public java.util.List<CheckStatus.Metadata> getMetadataList() {
        if (metadataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metadata_);
        } else {
          return metadataBuilder_.getMessageList();
        }
      }
      public int getMetadataCount() {
        if (metadataBuilder_ == null) {
          return metadata_.size();
        } else {
          return metadataBuilder_.getCount();
        }
      }
      public CheckStatus.Metadata getMetadata(int index) {
        if (metadataBuilder_ == null) {
          return metadata_.get(index);
        } else {
          return metadataBuilder_.getMessage(index);
        }
      }
      public Builder setMetadata(
          int index, CheckStatus.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetadataIsMutable();
          metadata_.set(index, value);
          onChanged();
        } else {
          metadataBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMetadata(
          int index, CheckStatus.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.set(index, builderForValue.build());
          onChanged();
        } else {
          metadataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMetadata(CheckStatus.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetadataIsMutable();
          metadata_.add(value);
          onChanged();
        } else {
          metadataBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMetadata(
          int index, CheckStatus.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetadataIsMutable();
          metadata_.add(index, value);
          onChanged();
        } else {
          metadataBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMetadata(
          CheckStatus.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.add(builderForValue.build());
          onChanged();
        } else {
          metadataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMetadata(
          int index, CheckStatus.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.add(index, builderForValue.build());
          onChanged();
        } else {
          metadataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMetadata(
          java.lang.Iterable<? extends CheckStatus.Metadata> values) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          super.addAll(values, metadata_);
          onChanged();
        } else {
          metadataBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMetadata() {
        if (metadataBuilder_ == null) {
          metadata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          metadataBuilder_.clear();
        }
        return this;
      }
      public Builder removeMetadata(int index) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.remove(index);
          onChanged();
        } else {
          metadataBuilder_.remove(index);
        }
        return this;
      }
      public CheckStatus.Metadata.Builder getMetadataBuilder(
          int index) {
        return getMetadataFieldBuilder().getBuilder(index);
      }
      public CheckStatus.MetadataOrBuilder getMetadataOrBuilder(
          int index) {
        if (metadataBuilder_ == null) {
          return metadata_.get(index);  } else {
          return metadataBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends CheckStatus.MetadataOrBuilder> 
           getMetadataOrBuilderList() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metadata_);
        }
      }
      public CheckStatus.Metadata.Builder addMetadataBuilder() {
        return getMetadataFieldBuilder().addBuilder(
            CheckStatus.Metadata.getDefaultInstance());
      }
      public CheckStatus.Metadata.Builder addMetadataBuilder(
          int index) {
        return getMetadataFieldBuilder().addBuilder(
            index, CheckStatus.Metadata.getDefaultInstance());
      }
      public java.util.List<CheckStatus.Metadata.Builder> 
           getMetadataBuilderList() {
        return getMetadataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CheckStatus.Metadata, CheckStatus.Metadata.Builder, CheckStatus.MetadataOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CheckStatus.Metadata, CheckStatus.Metadata.Builder, CheckStatus.MetadataOrBuilder>(
                  metadata_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Bundle)
    }
    
    static {
      defaultInstance = new Bundle(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Bundle)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Metric_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Metric_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Status_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Metadata_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Bundle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Bundle_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CheckStatus.proto\"\230\001\n\006Metric\022\014\n\004name\030\001" +
      " \002(\t\022\022\n\nmetricType\030\002 \002(\005\022\020\n\010valueDbl\030\003 \001" +
      "(\001\022\020\n\010valueI64\030\004 \001(\003\022\021\n\tvalueUI64\030\005 \001(\004\022" +
      "\020\n\010valueI32\030\006 \001(\005\022\021\n\tvalueUI32\030\007 \001(\r\022\020\n\010" +
      "valueStr\030\010 \001(\t\"L\n\006Status\022\021\n\tavailable\030\001 " +
      "\002(\005\022\r\n\005state\030\002 \002(\005\022\020\n\010duration\030\003 \002(\005\022\016\n\006" +
      "status\030\004 \002(\t\"&\n\010Metadata\022\013\n\003key\030\001 \002(\t\022\r\n" +
      "\005value\030\002 \002(\t\"X\n\006Bundle\022\027\n\006status\030\001 \001(\0132\007" +
      ".Status\022\030\n\007metrics\030\002 \003(\0132\007.Metric\022\033\n\010met" +
      "adata\030\003 \003(\0132\t.Metadata"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Metric_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Metric_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Metric_descriptor,
              new java.lang.String[] { "Name", "MetricType", "ValueDbl", "ValueI64", "ValueUI64", "ValueI32", "ValueUI32", "ValueStr", },
              CheckStatus.Metric.class,
              CheckStatus.Metric.Builder.class);
          internal_static_Status_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Status_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Status_descriptor,
              new java.lang.String[] { "Available", "State", "Duration", "Status", },
              CheckStatus.Status.class,
              CheckStatus.Status.Builder.class);
          internal_static_Metadata_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Metadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Metadata_descriptor,
              new java.lang.String[] { "Key", "Value", },
              CheckStatus.Metadata.class,
              CheckStatus.Metadata.Builder.class);
          internal_static_Bundle_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Bundle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Bundle_descriptor,
              new java.lang.String[] { "Status", "Metrics", "Metadata", },
              CheckStatus.Bundle.class,
              CheckStatus.Bundle.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
