					<!--h2>Search</h2-->
					<h4>&quot;ngm&quot; and &quot;my shot&quot;</h4>
					<p>5360 data points found</p>
					<div id="searchform" style="margin:.5em 0 2em 0;padding-bottom:1em;border-bottom: solid 1px #e6e4e5;">
					 <form name="form2" id="form2">
						<fieldset>
						<legend style="display:none;">Search</legend>
						<label for="search_new"><input type="radio" name="search_new" id="search_new" value="New Search" /> New Search</label> &nbsp;&nbsp;&nbsp;
						<label for="search_within"><input type="radio" name="search_within" id="search_within" value="Search within Result" /> Search within Result</label><br />
						<label for="keyword" style="display:none;">Keyword</label> <input type="text" id="keyword" style="width:220px;" /> <input type="submit" value="Submit" />
						</fieldset>
					</form>
					</div>
					<div id="searchlist">
						<ul>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li class="txt"><a href="#">text data sed do eiusmod tempor incididunt ut labore</a></li>
							<li class="txt"><a href="#">text data sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li class="txt"><a href="#">text data sed do eiusmod tempor incididunt ut labore</a></li>
							<li class="txt"><a href="#">text data sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li class="txt"><a href="#">text data sed do eiusmod tempor incididunt ut labore</a></li>
							<li class="txt"><a href="#">text data sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li class="txt"><a href="#">text data sed do eiusmod tempor incididunt ut labore</a></li>
							<li class="txt"><a href="#">text data sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a></li>
						</ul>
					</div>
