		<h3 id="graph_controls">Graph Controls</h3>
		<span class="search">
			<div class="tabs">
				<ul class="tabNavigation">
					<li class="first"><a href="#first">Search</a></li>
					<li class="second"><a href="#second">Browse All Data</a></li>
					<li class="third"><a href="#third">Saved Graphs</a></li>
				</ul><br clear="all" />
		
				<div id="first"><!-- search -->
				<?php include('search_simple.inc') ?>
				</div>
				<div id="second"><!-- browse -->
				<?php include('search_browser.inc') ?>
				</div>
				<div id="third"><!-- saved graphs -->
				<?php include('search_saved_graphs.inc') ?>
				</div>
			</div>
		</span>
