					<h4>640 graphs found</h4>
					<div class="accordion2">
						<h4>Narrow results by user</h4>
						<div>
							<form name="form" id="form">
								<label for="jumpMenu">User:</label>
								<select name="jumpMenu" id="jumpMenu" onchange="MM_jumpMenu('parent',this,0)">
									<option>All users</option>
									<option>theo@omniti.com</option>
									<option>loremipsum@mail.freelotto.com</option>
								</select>
							</form>
						</div>
						<h4>Narrow results by keyword</h4>
						<div>
							 <form name="form3" id="form3">
								<fieldset>
								<label for="keyword2" style="display:none;">Keyword</label> <input type="text" id="keyword2" value="keyword" style="width:200px;" /> <input type="submit" value="Submit" /> <input type="submit" value="Clear" />
								</fieldset>
							</form>
						</div>
					</div>
					<div style="margin:1em 0;padding:1em 0;border-top:1px solid #e6e4e5;border-bottom:2px none #e6e4e5;">
					<form name="form" id="form">
						<label for="jumpMenu">Sort by:</label>
						<select name="jumpMenu" id="jumpMenu" onchange="MM_jumpMenu('parent',this,0)">
							<option>Date New to Old</option>
							<option>Date Old to New</option>
							<option>User A to Z</option>
							<option>User Z to A</option>
						</select>
					</form>
					</div>
					
					<div id="graphlist">
						<ul>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a><ul><li class="xx">theo@omniti.com</li><li>YY/MM/DD</li><li><a href="#" class="addtows" title="Add to Worksheet"><em>Add</em></a></li></ul></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a><ul><li class="xx">theo@omniti.com</li><li>YY/MM/DD</li><li><a href="#" class="addtows" title="Add to Worksheet"><em>Add</em></a></li></ul></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a><ul><li class="xx">theo@omniti.com</li><li>YY/MM/DD</li><li><a href="#" class="addtows" title="Add to Worksheet"><em>Add</em></a></li></ul></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a><ul><li class="xx">theo@omniti.com</li><li>YY/MM/DD</li><li><a href="#" class="addtows" title="Add to Worksheet"><em>Add</em></a></li></ul></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a><ul><li class="xx">theo@omniti.com</li><li>YY/MM/DD</li><li><a href="#" class="addtows" title="Add to Worksheet"><em>Add</em></a></li></ul></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a><ul><li class="xx">theo@omniti.com</li><li>YY/MM/DD</li><li><a href="#" class="addtows" title="Add to Worksheet"><em>Add</em></a></li></ul></li>
							<li><a href="#">sed do eiusmod tempor incididunt ut labore</a><ul><li class="xx">theo@omniti.com</li><li>YY/MM/DD</li><li><a href="#" class="addtows" title="Add to Worksheet"><em>Add</em></a></li></ul></li>
						</ul>
					</div>
