		<h3 id="worksheet_controls">Worksheet Controls</h3>
                <span class="search">
                        <div class="ws-tabs">
                                <ul class="tabNavigation">
                                        <li class="ws-first"><a href="#ws-first">WorkSheets</a></li>
                                        <li class="ws-second"><a href="#ws-second">Find Graphs</a></li>
                                </ul><br clear="all" />

                                <div id="ws-first"><!-- search -->
                                <?php include('ws_search_simple.inc') ?>
                                </div>
                                <div id="ws-second"><!-- saved graphs -->
                                <?php include('ws_search_graphs.inc') ?>
                                </div>
                        </div>
                </span>
