<span class="rememberWorksheet"></span>
<span class="blankWorksheet">New Blank</span>
<span class="editWorksheet">Editing!</span>
<span class="permalink" id="wpermalink"><a href="">Link</a></span>
<h2 id="worksheetTitle">Worksheet Title</h2>
<p/>

<div id="ws_datetool">
	<div class="zoom">
		<dl>
			<dt>Zoom:</dt>
			<dd><a href="#" class="first datechoice">6h</a></dd>
			<dd><a href="#" class="datechoice">12h</a></dd>
			<dd><a href="#" class="datechoice">1d</a></dd>
			<dd><a href="#" class="datechoice">2d</a></dd>
			<dd><a href="#" class="datechoice">1w</a></dd>
			<dd><a href="#" class="selected datechoice">2w</a></dd>
			<dd><a href="#" class="datechoice">4w</a></dd>
			<dd><a href="#" class="datechoice">1y</a></dd>
		</dl>
	</div>
	<div class="range">
		<dl>
			<dt>Date Range:</dt>
			<dd><a href="" class="btn-slide">YYYY/MM/DD - YYYY/MM/DD</a></dd>
		</dl>
	</div>
<br style="clear:both; margin-bottom:0.5em;"/>
	<div id="ws_widgetCalendar" class="widgetCalendar"></div>
</div>

<div>
  <ul id="worksheet-graphs" />
  <br style="clear:left" />
</div>	
	<div id="streambox" style="display:none"></div>	
<div style="display:none">
	<div id="maingraph-template">
        <div class="plot-area" style="width:380px;height:180px"></div>
        <div class="plot-legend">legend</div>
        </div>
</div>

<div class="error"><p class="error" id="ws-tool-error"></p></div>

<div id="ws_payload">
</div>
