		<h3>Worksheet Controls</h3>
		<span class="worksheet">
			<div id="searchform" style="margin:1em 0 1em 0;padding-bottom:1em;border-bottom: solid 1px #c4c4c4;">
			<form name="form" id="form">
				<label for="jumpMenu">User:</label>
				<select name="jumpMenu" id="jumpMenu" onchange="MM_jumpMenu('parent',this,0)">
					<option>theo@omniti.com</option>
					<option>loremipsum@mail.freelotto.com</option>
				</select>
			</form>
			</div>
			<div style="clear:both;">
			<input name="New Worksheet" type="button" value="New worksheet" style="float:right;" />
			<h4 style="margin:.5em 0 1em 0;">20 Worksheets</h4>
			</div>
			<div id="worksheetlist">
				<ul>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li class="selected"><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
					<li><a href="#">sed do eiusmod tempor incididunt</a></li>
				</ul>
			</div>
		</span>
