<h4 id="ws-graph-searchterms"></h4>
<div id="ws-graph-searchform-container" style="margin:.5em 0 2em 0;padding-bottom:1em;border-bottom: solid 1px #e6e4e5;">
<form id="ws-graph-searchform">
  <fieldset>
  <p class="explain">Enter a term to search for graphs.</p>
  <legend style="display:none;">Search</legend>
  <label for="keyword" style="display:none;">Keyword</label> <input type="text" id="ws-graph-searchinput" style="width:220px;" /> <input type="submit" value="Search" />
  </fieldset>
</form>
</div>
<div id="ws-graphlist" class="graphlist">
  <p class="search-summary"></p>
  <p class="paginate"></p>
  <ul class="searchresults">
  </ul>
</div>
