<h4 id="ws-searchterms"></h4>
<div id="ws-searchform-container" style="margin:.5em 0 2em 0;padding-bottom:1em;border-bottom: solid 1px #e6e4e5;">
<form id="ws-searchform">
  <fieldset>
  <p class="explain">Enter a term to search for worksheets.</p>
  <legend style="display:none;">Search</legend>
  <label for="keyword" style="display:none;">Keyword</label> <input type="text" id="ws-searchinput" style="width:220px;" /> <input type="submit" value="Search" />
  </fieldset>
</form>
</div>
<div id="worksheetlist" class="worksheetlist">
  <p class="search-summary"/>
  <p class="paginate"/>
  <ul class="searchresults">
  </ul>
</div>
