
noit_b32.o noit_b32.lo: noit_b32.c ../noit_config.h noit_b64.h ../noit_defines.h \
  ../noitedit/strlcpy.h

noit_b64.o noit_b64.lo: noit_b64.c ../noit_config.h noit_b64.h ../noit_defines.h \
  ../noitedit/strlcpy.h

noit_btrie.o noit_btrie.lo: noit_btrie.c ../noit_defines.h ../noit_config.h \
  ../noitedit/strlcpy.h ../utils/noit_btrie.h

noit_getip.o noit_getip.lo: noit_getip.c ../noit_config.h ../utils/noit_getip.h \
  ../noit_defines.h ../noitedit/strlcpy.h ../eventer/eventer.h \
  ../utils/noit_log.h ../utils/noit_hash.h ../utils/noit_atomic.h \
  ../eventer/eventer_POSIX_fd_opset.h ../eventer/eventer_SSL_fd_opset.h \
  ../eventer/eventer_jobq.h ../utils/noit_sem.h

noit_hash.o noit_hash.lo: noit_hash.c ../noit_config.h noit_hash.h

noit_lockfile.o noit_lockfile.lo: noit_lockfile.c ../noit_config.h \
  ../utils/noit_lockfile.h ../noit_defines.h ../noitedit/strlcpy.h

noit_log.o noit_log.lo: noit_log.c ../noit_defines.h ../noit_config.h \
  ../noitedit/strlcpy.h ../utils/noit_log.h ../utils/noit_hash.h \
  ../utils/noit_atomic.h ../libnoit_dtrace_probes.h

noit_memory.o noit_memory.lo: noit_memory.c ../utils/noit_log.h ../noit_defines.h \
  ../noit_config.h ../noitedit/strlcpy.h ../utils/noit_hash.h

noit_mkdir.o noit_mkdir.lo: noit_mkdir.c ../noit_config.h ../utils/noit_mkdir.h \
  ../noit_defines.h ../noitedit/strlcpy.h ../utils/noit_log.h \
  ../utils/noit_hash.h

noit_security.o noit_security.lo: noit_security.c ../noit_defines.h ../noit_config.h \
  ../noitedit/strlcpy.h ../utils/noit_log.h ../utils/noit_hash.h \
  ../utils/noit_security.h

noit_sem.o noit_sem.lo: noit_sem.c ../noit_defines.h ../noit_config.h \
  ../noitedit/strlcpy.h ../utils/noit_sem.h

noit_skiplist.o noit_skiplist.lo: noit_skiplist.c ../noit_defines.h ../noit_config.h \
  ../noitedit/strlcpy.h noit_skiplist.h

noit_str.o noit_str.lo: noit_str.c ../noit_defines.h ../noit_config.h \
  ../noitedit/strlcpy.h

noit_watchdog.o noit_watchdog.lo: noit_watchdog.c ../noit_defines.h ../noit_config.h \
  ../noitedit/strlcpy.h ../eventer/eventer.h ../utils/noit_log.h \
  ../utils/noit_hash.h ../utils/noit_atomic.h \
  ../eventer/eventer_POSIX_fd_opset.h ../eventer/eventer_SSL_fd_opset.h \
  ../eventer/eventer_jobq.h ../utils/noit_sem.h ../utils/noit_watchdog.h
