
bundle.pb-c.o bundle.pb-c.lo: bundle.pb-c.c bundle.pb-c.h

noit_check.o noit_check.lo: noit_check.c noit_config.h \
  noit_mtev_bridge.h \
  noit_dtrace_probes.h noit_check.h  \
  noit_metric.h noit_module.h  \
  noit_check_tools.h noit_check_tools_shared.h noit_check_resolver.h

noit_check_log.o noit_check_log.lo: noit_check_log.c  \
  noit_dtrace_probes.h \
  noit_mtev_bridge.h  \
  noit_check.h \
  noit_metric.h \
  noit_filters.h bundle.pb-c.h noit_check_log_helpers.h

noit_check_log_helpers.o noit_check_log_helpers.lo: noit_check_log_helpers.c \
  noit_mtev_bridge.h bundle.pb-c.h noit_metric.h \
  noit_check_log_helpers.h

noit_check_resolver.o noit_check_resolver.lo: noit_check_resolver.c noit_config.h \
  noit_mtev_bridge.h

noit_check_rest.o noit_check_rest.lo: noit_check_rest.c  \
  noit_mtev_bridge.h \
  noit_filters.h noit_check.h noit_metric.h noit_check_resolver.h \
  noit_check_tools.h noit_module.h  \
  noit_check_tools_shared.h

noit_check_tools.o noit_check_tools.lo: noit_check_tools.c \
  noit_mtev_bridge.h \
  noit_dtrace_probes.h noit_check_tools.h \
  noit_module.h  \
  noit_check.h noit_metric.h \
  noit_check_tools_shared.h

noit_check_tools_shared.o noit_check_tools_shared.lo: noit_check_tools_shared.c \
  noit_check_tools.h \
  noit_module.h  \
  noit_check.h noit_metric.h \
  noit_check_tools_shared.h

noit_conf_checks.o noit_conf_checks.lo: noit_conf_checks.c \
  noit_filters.h noit_check.h \
  noit_metric.h noit_conf_checks.h \
  noit_check_tools.h noit_module.h  \
  noit_check_tools_shared.h

noit_filters.o noit_filters.lo: noit_filters.c  \
  noit_mtev_bridge.h \
  noit_check.h  noit_metric.h \
  noit_conf_checks.h noit_filters.h \

noit_filters_rest.o noit_filters_rest.lo: noit_filters_rest.c \
  noit_mtev_bridge.h \
  noit_filters.h noit_check.h noit_metric.h noit_check_tools.h \
  noit_module.h  \
  noit_check_tools_shared.h

noit_jlog_listener.o noit_jlog_listener.lo: noit_jlog_listener.c \
  noit_mtev_bridge.h \
  noit_jlog_listener.h

noit_livestream_listener.o noit_livestream_listener.lo: noit_livestream_listener.c \
  noit_mtev_bridge.h \
  noit_livestream_listener.h noit_check.h \
  noit_metric.h

noit_module.o noit_module.lo: noit_module.c  \
  noit_module.h \
  noit_check.h noit_metric.h noit_mtev_bridge.h module-online.h

noit_mtev_bridge.o noit_mtev_bridge.lo: noit_mtev_bridge.c \

noitd.o noitd.lo: noitd.c noit_config.h  \
  noit_mtev_bridge.h \
  noit_jlog_listener.h noit_check_rest.h noit_check.h noit_metric.h \
  noit_check_tools.h noit_module.h  \
  noit_check_tools_shared.h  \
  noit_livestream_listener.h \
  noit_conf_checks.h noit_filters.h man/noitd.usage.h

stratcon_datastore.o stratcon_datastore.lo: stratcon_datastore.c \
  noit_mtev_bridge.h \
  stratcon_datastore.h stratcon_realtime_http.h stratcon_ingest.h \
  stratcon_iep.h stratcon_jlog_streamer.h \
  noit_check.h noit_metric.h

stratcon_iep.o stratcon_iep.lo: stratcon_iep.c  \
  noit_mtev_bridge.h \
  noit_jlog_listener.h stratcon_jlog_streamer.h \
  stratcon_datastore.h \
  stratcon_realtime_http.h stratcon_iep.h noit_check.h \
  noit_metric.h

stratcon_ingest.o stratcon_ingest.lo: stratcon_ingest.c  \
  noit_mtev_bridge.h \
  stratcon_datastore.h stratcon_realtime_http.h stratcon_ingest.h \
  stratcon_iep.h stratcon_jlog_streamer.h \
  noit_check.h noit_metric.h

stratcon_jlog_streamer.o stratcon_jlog_streamer.lo: stratcon_jlog_streamer.c \
  noit_mtev_bridge.h \
  stratcon_dtrace_probes.h noit_jlog_listener.h stratcon_datastore.h \
  stratcon_realtime_http.h stratcon_jlog_streamer.h \
  stratcon_iep.h

stratcon_realtime_http.o stratcon_realtime_http.lo: stratcon_realtime_http.c \
  noit_mtev_bridge.h \
  noit_jlog_listener.h noit_check.h noit_metric.h \
  noit_check_log_helpers.h noit_livestream_listener.h \
  stratcon_realtime_http.h stratcon_jlog_streamer.h \
  stratcon_datastore.h

stratcond.o stratcond.lo: stratcond.c  \
  noit_mtev_bridge.h \
  noit_config.h noit_module.h  \
  noit_check.h noit_metric.h stratcon_jlog_streamer.h \
  stratcon_datastore.h stratcon_realtime_http.h stratcon_iep.h \
  man/stratcond.usage.h

udns/udns_codes.o udns/udns_codes.lo: udns/udns_codes.c
